name: Caché de dependencias Laravel

on: [push]

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            vendor
            ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - run: composer install --no-interaction --prefer-dist
