name: Análisis de Código (.NET SAST)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  codeql:
    name: CodeQL Scan
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Build only Web project
  run: |
    dotnet restore ./Distribuidora_La_Central.Web/Distribuidora_La_Central.Web.csproj
    dotnet build ./Distribuidora_La_Central.Web/Distribuidora_La_Central.Web.csproj --no-restore --configuration Release

      - name: Analyze
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"

  semgrep:
    name: Semgrep SAST Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar Semgrep
        run: |
          pip install semgrep

      - name: Ejecutar Semgrep
        run: |
          semgrep --config=p/ci --error --json > semgrep-results.json || true

      - name: Subir resultados como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-results
          path: semgrep-results.json

