name: Escaneo de Dependencias (.NET)

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  dependency-check:
    name: OWASP Dependency Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Instalar Java (requerido para OWASP)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Descargar OWASP Dependency Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v10.0.3/dependency-check-10.0.3-release.zip
          unzip dependency-check-10.0.3-release.zip -d ./dependency-check

      - name: Ejecutar análisis de dependencias
        run: |
          ./dependency-check/dependency-check/bin/dependency-check.sh \
          --project "Distribuidora_La_Central" \
          --scan . \
          --format "HTML" \
          --out ./dependency-report

      - name: Subir reporte como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: dependency-report
          path: dependency-report

  github-dependency-review:
    name: GitHub Dependency Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Escanear dependencias con GitHub
        uses: actions/dependency-review-action@v4

