name: Dotnet Version

on: [push]

jobs:
  check-dotnet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Mostrar versión de .NET
        run: dotnet --version
