name: Generar artefactos en C#

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - run: dotnet publish -c Release -o out

      - uses: actions/upload-artifact@v4
        with:
          name: app-publish
          path: out
