name: Laravel Environment

on: [push]

jobs:
  check-laravel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Instalar Composer
        run: sudo apt-get update && sudo apt-get install -y composer

      - name: Mostrar versiones
        run: |
          php --version
          composer --version
