name: Reporte Consolidado
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download code-analysis artifacts
        uses: actions/download-artifact@v4
        with:
          name: code-analysis-artifacts
          path: reports/code

      - name: Download dependency-scan artifacts
        uses: actions/download-artifact@v4
        with:
          name: dependency-scan-artifacts
          path: reports/deps

      - name: Generate consolidated report
        run: |
          mkdir -p reports/final
          cat << 'EOF' > reports/final/SECURITY_REPORT.md
          # 📊 Informe de Seguridad — Distribuidora La Central

          ## Resumen Ejecutivo
          - Calificación de seguridad general: TBD
          - Vulnerabilidades críticas: TBD
          - Vulnerabilidades altas: TBD

          ## Hallazgos Críticos
          | ID | Severidad | Tipo | Ubicación | Recomendación |
          |----|-----------|------|-----------|---------------|
          # aquí extraerías de los reportes descargados

          ## Análisis por Categoría
          ### 🔍 Código
          - Código analizado con CodeQL + Sonar / ESLint
          # ...
          ### 📦 Dependencias
          - Vulnerabilidades conocidas detectadas con Dependency-Check
          - Paquetes desactualizados listados en outdated-packages.json

          ## Recomendaciones Prioritarias
          1. Remediar vulnerabilidades críticas inmediatamente
          2. Actualizar dependencias
          3. Fortalecer reglas de análisis

          ## Métricas de Mejora
          - Cobertura de análisis: TBD
          - Tendencia: comparar con reportes previos
          EOF

      - name: Upload final report
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: reports/final/SECURITY_REPORT.md

      # (Opcional) Publicar a GitHub Pages
      - name: Deploy to GitHub Pages
        if: github.repository == 'Uroboros66/Distribuidora_La_Central-Dise-oTerminado'
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: reports/final
          # configura rama y token si es necesario
