name: C# Roslyn Analyzers

on: [push, pull_request]

jobs:
  analyze:
    runs-on: windows-latest  # usa Windows, no Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore MAUI workloads
        run: dotnet workload restore

      - name: Install MAUI workloads
        run: |
          dotnet workload install maui
          dotnet workload install maui-android

      - name: Restore dependencies
        run: dotnet restore

      - name: Run Roslyn Analyzers
        run: dotnet build --no-restore /warnaserror
