name: Validación de estilo en Laravel

on: [push, pull_request]

jobs:
  pint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Instalar dependencias
        run: composer install --no-interaction --prefer-dist

      - name: Validar estilo con Pint
        run: ./vendor/bin/pint --test
